# Generated by Django 4.2.1 on 2023-06-04 14:15

import typing

from django.db import migrations, models

import django_pydantic_field._migration_serializers
import django_pydantic_field.fields
import tests.sample_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "opt_meta",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default='{"type":"frame"}',
                        null=True,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(None),
                    ),
                ),
                (
                    "meta",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None, default='{"type":"frame"}', schema=tests.sample_app.models.BuildingMeta
                    ),
                ),
                (
                    "meta_schema_list",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None, default=list, schema=typing.ForwardRef("ty.List[BuildingMeta]")
                    ),
                ),
                (
                    "meta_typing_list",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None, default=list, schema=django_pydantic_field._migration_serializers.GenericContainer(None)
                    ),
                ),
                (
                    "meta_untyped_list",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None, default=list, schema=django_pydantic_field._migration_serializers.GenericContainer(list)
                    ),
                ),
                (
                    "meta_untyped_builtin_list",
                    django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, schema=list),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostponedBuilding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "meta",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None, default='{"type":"frame"}', schema=tests.sample_app.models.BuildingMeta
                    ),
                ),
                (
                    "meta_builtin_list",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=list,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (tests.sample_app.models.BuildingMeta,)
                        ),
                    ),
                ),
                (
                    "meta_typing_list",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None, default=list, schema=django_pydantic_field._migration_serializers.GenericContainer(None)
                    ),
                ),
                (
                    "meta_untyped_list",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None, default=list, schema=django_pydantic_field._migration_serializers.GenericContainer(list)
                    ),
                ),
                (
                    "meta_untyped_builtin_list",
                    django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, schema=list),
                ),
            ],
        ),
    ]
