# Generated by Django 4.1.7 on 2023-02-27 14:41

import typing

from django.db import migrations, models

import django_pydantic_field._migration_serializers
import django_pydantic_field.fields
import tests.conftest


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SampleForwardRefModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotated_field",
                    django_pydantic_field.fields.PydanticSchemaField(config=None, default=dict, schema="SampleSchema"),
                ),
                (
                    "field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=dict,
                        schema=typing.ForwardRef("SampleSchema"),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config={"allow_mutation": False, "frozen": True},
                        schema=tests.conftest.InnerSchema,
                    ),
                ),
                (
                    "sample_list",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (tests.conftest.InnerSchema,)
                        ),
                    ),
                ),
                (
                    "sample_seq",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=list,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (tests.conftest.InnerSchema,)
                        ),
                    ),
                ),
            ],
        ),
    ]
