# Generated by Django 5.0.3 on 2024-03-25 22:22

import typing_extensions
import annotated_types
import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import tests.conftest
import tests.test_app.models
import types
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "example_field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default={"count": 1},
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.test_app.models.ExampleSchema,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleForwardRefModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "annotated_field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.test_app.models.SampleSchema,
                    ),
                ),
                (
                    "field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.test_app.models.SampleSchema,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sample_field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.conftest.InnerSchema,
                    ),
                ),
                (
                    "sample_list",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            list, (tests.conftest.InnerSchema,)
                        ),
                    ),
                ),
                (
                    "sample_seq",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            list, (tests.conftest.InnerSchema,)
                        ),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleModelAnnotated",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "annotated_field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            typing_extensions.Annotated,
                            (
                                django_pydantic_field.compat.django.GenericContainer(typing.Union, (int, float)),
                                django_pydantic_field.compat.django.FieldInfoContainer(
                                    None, (annotated_types.Gt(gt=0),), {"title": "Annotated Field"}
                                ),
                            ),
                        ),
                    ),
                ),
                (
                    "annotated_schema",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            typing_extensions.Annotated,
                            (
                                django_pydantic_field.compat.django.GenericContainer(typing.Union, (int, float)),
                                django_pydantic_field.compat.django.FieldInfoContainer(
                                    None, (annotated_types.Gt(gt=0),), {}
                                ),
                            ),
                        ),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleModelWithRoot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "root_field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.test_app.models.RootSchema,
                    ),
                ),
            ],
        ),
    ]
