# Generated by Django 3.2.23 on 2023-11-21 14:37

import django.core.serializers.json
from django.db import migrations, models
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import tests.conftest
import tests.test_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SampleForwardRefModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "annotated_field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.test_app.models.SampleSchema,
                    ),
                ),
                (
                    "field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.test_app.models.SampleSchema,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sample_field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.conftest.InnerSchema,
                    ),
                ),
                (
                    "sample_list",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            list, (tests.conftest.InnerSchema,)
                        ),
                    ),
                ),
                (
                    "sample_seq",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            list, (tests.conftest.InnerSchema,)
                        ),
                    ),
                ),
            ],
        ),
    ]
