# Generated by Django 5.0.1 on 2024-01-27 18:30

import django.core.serializers.json
import django_pydantic_field.fields
import tests.test_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "example_field",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default={"count": 1},
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.test_app.models.ExampleSchema,
                    ),
                ),
            ],
        ),
    ]
