# Generated by Django 5.0.1 on 2024-03-08 14:35

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import tests.test_app.models
import types
import typing
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_examplemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplemodel",
            name="sample_null_root_schema",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    typing.Union,
                    (
                        tests.test_app.models.RootSchema,
                        types.NoneType,
                    ),
                ),
            ),
        ),
        migrations.AddField(
            model_name="samplemodel",
            name="sample_root_schema",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=[],
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=tests.test_app.models.RootSchema,
            ),
        ),
    ]
